# Generated by Django 5.2.7 on 2025-10-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la station')),
                ('location', models.CharField(max_length=200, verbose_name='Localisation')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
